name: hyll_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  google_fonts: ^5.1.0
  collection: ^1.17.1
  cached_video_player: ^2.0.4
  iconsax: ^0.0.8
  video_thumbnail: ^0.5.3
  path_provider: ^2.0.15
  readmore: ^2.2.0
  shimmer: ^3.0.0
  chewie: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
