// Generated by https://quicktype.io

import 'package:hyll_test/domain/domain.dart';

class Adventure {
  const Adventure({
    this.id,
    this.pk,
    this.status,
    this.title,
    this.areaLocation,
    this.startingLocation,
    this.tags,
    this.activity,
    this.activityId,
    this.primaryImage,
    this.primaryVideo,
    this.thumbnail,
    this.activityIcon,
    this.badges,
    this.bucketListCount,
    this.contents,
    this.supplyInfo,
    this.gridInfo,
    this.ticketOptional,
    this.bucketListedByFollowing,
    this.primaryDescription,
    this.description,
    this.facts,
  });

  final int? id;
  final int? pk;
  final String? status;
  final String? title;
  final Location? areaLocation;
  final Location? startingLocation;
  final List<String>? tags;
  final String? activity;
  final int? activityId;
  final String? primaryImage;
  final String? primaryVideo;
  final String? thumbnail;
  final String? activityIcon;
  final List<dynamic>? badges;
  final int? bucketListCount;
  final List<Content>? contents;
  final SupplyInfo? supplyInfo;
  final List<GridInfo>? gridInfo;
  final bool? ticketOptional;
  final List<dynamic>? bucketListedByFollowing;
  final String? primaryDescription;
  final String? description;
  final List<dynamic>? facts;
}
